working s6 overlay

diff --git a/s6-services/jackd/run b/s6-services/jackd/run
--- a/s6-services/jackd/run
+++ b/s6-services/jackd/run
@@ -1,2 +1,12 @@
-#!/usr/bin/execlineb -P
-/usr/bin/jackd -R -P 80 -S -t 200 -C /tmp/jack-internal-session.conf -d alsa -d hw:%{CARD}s -r 48000 -p 128 -n 2 -X seq
+#!/command/with-contenv sh
+set -e
+
+# --- Safety check for CARD ---
+if [ -z "$CARD" ]; then
+    echo "[ERROR] Environment variable CARD is not set. Exiting." >&2
+    exit 1
+fi
+touch /tmp/jack-internal-session.conf
+exec /usr/bin/jackd -R -P 80 -S -t 200 \
+    -C /tmp/jack-internal-session.conf \
+    -d alsa -d hw:${CARD} -r 48000 -p 128 -n 2 -X seq
